---
- name: "Add Node.js from source"
  become: true
  shell: |
    curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
- name: "Install Node.js 16"
  become: true
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "move env variables to /etc/profile.d/"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/
